version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:5000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: