name: CI/CD for Python 3-Tier App

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/python-frontend:latest

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/python-backend:latest

 
  deploy:
    name: Deploy to EC2 Instance
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Clone repo (first time) or pull latest changes
          if [ ! -d "three-tier-python-app" ]; then
            git clone https://github.com/suyogkumawat/three-tier.git
          else
            cd three-tier
            git pull origin main
            cd ..
          fi

          # Navigate to the repo
          cd three-tier

          # Pull latest Docker images
          docker pull ${{ secrets.DOCKERHUB_USER }}/python-frontend:latest
          docker pull ${{ secrets.DOCKERHUB_USER }}/python-backend:latest

          # Restart containers
          docker compose down
          docker compose up -d
          EOF
